### ISSUE TITLE
Getting the sounds before it even executing the code

### ISSUE THREAD

**Issue by TheIceNinja** [JustNOTRO/EssentialCommands#2]
https://github.com/JustNOTRO/EssentialCommands/blob/a2d9fc0dbe7742766298e85c60c47c6cb0122fdc/src/main/java/me/notro/essentialcommands/commands/BuildCommand.java#L20

**Comment by JustNOTRO** [comment]
Hello, the sections mentioned **sound.commands** has been removed recently.

Thanks for your review.
