### ISSUE TITLE
Thats bad, just use StringBuilder to fix that

### ISSUE THREAD

**Issue by TheIceNinja** [JustNOTRO/EssentialCommands#5]
https://github.com/JustNOTRO/EssentialCommands/blob/a2d9fc0dbe7742766298e85c60c47c6cb0122fdc/src/main/java/me/notro/essentialcommands/commands/MessageCommand.java#L48

**Comment by JustNOTRO** [comment]
Thanks for your review, All bad usage of String concatenation has been removed, will be seen next commit.
