### ISSUE TITLE
The name of the class

### ISSUE THREAD

**Issue by TheIceNinja** [JustNOTRO/EssentialCommands#6]
https://github.com/JustNOTRO/EssentialCommands/blob/a2d9fc0dbe7742766298e85c60c47c6cb0122fdc/src/main/java/me/notro/essentialcommands/systems/KitManager.java#L14

**Comment by JustNOTRO** [comment]
Hello, 
Could you please give a suggestion for a better name for the mentioned class?

Thanks.
