### ISSUE TITLE
No! just use logger

### ISSUE THREAD

**Issue by TheIceNinja** [JustNOTRO/EssentialCommands#7]
https://github.com/JustNOTRO/EssentialCommands/blob/a2d9fc0dbe7742766298e85c60c47c6cb0122fdc/src/main/java/me/notro/essentialcommands/EssentialCommands.java#L24

```java
   getLogger().info();
```

**Comment by JustNOTRO** [comment]
@TheIceNinja 
Thanks for your review on this subject, I've fixed it to:  `getLogger().info();`,  I appreciate the review, now I sort of know the meaning of Dependency Injection.
